[package]
name = "piston"
version = "0.1.0"
authors = ["Juan López Rubio <j.lopez.r@gmail.com>"]

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
