[package]
name = "nickel"
version = "0.1.0"
authors = ["Juan López Rubio <j.lopez.r@gmail.com>"]

[dependencies]
nickel = "*"
mongodb = "*"
bson = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
jwt = "*"
hyper = "*"
rust-crypto = "*"
